<?php
/** 
 * code generated by vog
 * https://github.com/MarvinWank/vog
 */
declare(strict_types=1);

namespace App\Value;


use UnexpectedValueException;

final class AddRecipeRequestDto implements ValueObject
{
    private string $title;
    private string $dietStyle;
    private string $cuisine;
    private int $timeToPrepare;
    private array $ingredients;

    public function __construct (
        string $title,
        string $dietStyle,
        string $cuisine,
        int $timeToPrepare,
        array $ingredients
    ) {
        $this->title = $title;
        $this->dietStyle = $dietStyle;
        $this->cuisine = $cuisine;
        $this->timeToPrepare = $timeToPrepare;
        $this->ingredients = $ingredients;
    }
    
    public function getTitle(): string 
    {
        return $this->title;
    }
    
    public function getDietStyle(): string 
    {
        return $this->dietStyle;
    }
    
    public function getCuisine(): string 
    {
        return $this->cuisine;
    }
    
    public function getTimeToPrepare(): int 
    {
        return $this->timeToPrepare;
    }
    
    public function getIngredients(): array 
    {
        return $this->ingredients;
    }
    
    public function withTitle(string $title): self 
    {
        return new self(
            $title,
            $this->dietStyle,
            $this->cuisine,
            $this->timeToPrepare,
            $this->ingredients
        );
    }
    
    public function withDietStyle(string $dietStyle): self 
    {
        return new self(
            $this->title,
            $dietStyle,
            $this->cuisine,
            $this->timeToPrepare,
            $this->ingredients
        );
    }
    
    public function withCuisine(string $cuisine): self 
    {
        return new self(
            $this->title,
            $this->dietStyle,
            $cuisine,
            $this->timeToPrepare,
            $this->ingredients
        );
    }
    
    public function withTimeToPrepare(int $timeToPrepare): self 
    {
        return new self(
            $this->title,
            $this->dietStyle,
            $this->cuisine,
            $timeToPrepare,
            $this->ingredients
        );
    }
    
    public function withIngredients(array $ingredients): self 
    {
        return new self(
            $this->title,
            $this->dietStyle,
            $this->cuisine,
            $this->timeToPrepare,
            $ingredients
        );
    }
    
    public function toArray(): array
    {
        return [
            'title' => $this->title,
            'dietStyle' => $this->dietStyle,
            'cuisine' => $this->cuisine,
            'timeToPrepare' => $this->timeToPrepare,
            'ingredients' => $this->ingredients,
        ];
    }
    
    public static function fromArray(array $array): self
    {
        if (!array_key_exists('title', $array)) {
            throw new UnexpectedValueException('Array key title does not exist');
        }
        
        if (!array_key_exists('dietStyle', $array)) {
            throw new UnexpectedValueException('Array key dietStyle does not exist');
        }
        
        if (!array_key_exists('cuisine', $array)) {
            throw new UnexpectedValueException('Array key cuisine does not exist');
        }
        
        if (!array_key_exists('timeToPrepare', $array)) {
            throw new UnexpectedValueException('Array key timeToPrepare does not exist');
        }
        
        if (!array_key_exists('ingredients', $array)) {
            throw new UnexpectedValueException('Array key ingredients does not exist');
        }
        
        return new self(
            $array['title'],
            $array['dietStyle'],
            $array['cuisine'],
            $array['timeToPrepare'],
            $array['ingredients']
        );
    }
        
    private function valueToArray($value)
    {
        if (method_exists($value, 'toArray')) {
            return $value->toArray();
        }
        
        return (string) $value;
    }    
    public function equals($value): bool
    {
        $ref = $this->toArray();
        $val = $value->toArray();
        
        return ($ref === $val);
    }
}