<?php

declare(strict_types=1);

namespace App\Value;

/**
 * Generated by prolic/fpp - do not edit !!!
 * @codeCoverageIgnore
 */
final class DietStyle
{
    public const ALLES = 0;
    public const VEGETARISCH = 1;
    public const VEGAN = 2;
    public const Options = ['ALLES', 'VEGETARISCH', 'VEGAN'];

    private string $name;
    private int $value;

    public static function ALLES(): self
    {
        return new self('ALLES', 0);
    }

    public static function VEGETARISCH(): self
    {
        return new self('VEGETARISCH', 1);
    }

    public static function VEGAN(): self
    {
        return new self('VEGAN', 2);
    }

    private function __construct(string $name, int $value)
    {
        $this->name = $name;
        $this->value = $value;
    }

    public static function fromName(string $name): self
    {
        foreach (self::Options as $i => $n) {
            if ($n === $name) {
                return new self($n, $i);
            }
        }

        throw new \InvalidArgumentException('Unknown enum name given');
    }

    public static function fromValue(int $value): self
    {
        if (! isset(self::Options[$value])) {
            throw new \InvalidArgumentException('Unknown enum value given');
        }

        return new self(self::Options[$value], $value);
    }

    public function equals(?self $other): bool
    {
        return null !== $other && $this->name === $other->name;
    }

    public function name(): string
    {
        return $this->name;
    }

    public function value(): int
    {
        return $this->value;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function toString(): string
    {
        return $this->name;
    }
}
