<?php
/** 
 * code generated by vog
 * https://github.com/MarvinWank/vog
 */
declare(strict_types=1);

namespace App\Value;


use UnexpectedValueException;

final class RecipeSet implements Set
{        
    private array $items;
        
    private function __construct(array $items = [])
    {
        $this->items = $items;
    }
    public static function fromArray(array $items) {
        foreach ($items as $key => $item) {
            $type = gettype($item);
            switch ($type) {
                case 'object':
                    if (!$item instanceof Recipe){
                        throw new UnexpectedValueException('array expects items of Recipe but has ' . $type . ' on index ' . $key); 
                    }    
                    break;
                case 'array':
                    if(is_a(Recipe::class, ValueObject::class, true) || is_a(Recipe::class, Set::class, true)) {
                        $items[$key] = Recipe::fromArray($item);
                    } else {
                        throw new UnexpectedValueException('fromArray can not create Recipe from array on index ' . $key);
                    }
                    break;    
                case 'string':
                    if(is_a(Recipe::class, Enum::class, true)) {
                        $items[$key] = Recipe::fromName($item);
                    } else {
                        throw new UnexpectedValueException('fromArray can not create Recipe from string on index ' . $key);
                    }
                    break;    
                default:
                    if ($type !== 'Recipe') {
                        throw new UnexpectedValueException('fromArray expects items of Recipe but has ' . $type . ' on index ' . $key);
                    }
                    break;
            }
            
        }
        return new self($items);
    }
    public function toArray() {
        $return = [];
        foreach ($this->items as $item) {
            if(is_a(Recipe::class, ValueObject::class, true) || is_a(Recipe::class, Set::class, true)) {
                $return[] = $item->toArray();
            }
            
            if(is_a(Recipe::class, Enum::class, true)) {
                $return[] = $item->toString();
            }
        }
        
        return $return;
    }
    public function equals(?self $other): bool
    {
        $ref = $this->toArray();
        $val = $other->toArray();
                
        return ($ref === $val);
    }
    
    public function count(): int
    {
        return count($this->items);
    }

    public function add(Recipe $item): self {
        $values = $this->toArray();
        $values[] = $item;
        return self::fromArray($values);
    }
    
    public function contains(Recipe $item): bool {
        return array_search($item, $this->items) !== false;
    }
    
    public function remove(Recipe $item): self {
        $values = $this->toArray();
        if(($key = array_search($item->toArray(), $values)) !== false) {
            unset($values[$key]);
        }
        $values = array_values($values);
        
        return self::fromArray($values);
    }
}