<?php
/** 
 * code generated by vog
 * https://github.com/MarvinWank/vog
 */
declare(strict_types=1);

namespace App\Value;


use UnexpectedValueException;
use BadMethodCallException;

class UserSet implements Set,\Countable,\ArrayAccess,\Iterator
{        
    private array $items;
    private int $position;
        
    private function __construct(array $items = [])
    {
        $this->position = 0;
        $this->items = $items;
    }    public static function fromArray(array $items) {
        foreach ($items as $key => $item) {
            $type = gettype($item);
            switch ($type) {
                case 'object':
                    if (!$item instanceof User){
                        throw new UnexpectedValueException('array expects items of User but has ' . $type . ' on index ' . $key); 
                    }    
                    break;
                case 'array':
                    if(is_a(User::class, ValueObject::class, true) || is_a(User::class, Set::class, true)) {
                        $items[$key] = User::fromArray($item);
                    } else {
                        throw new UnexpectedValueException('fromArray can not create User from array on index ' . $key);
                    }
                    break;    
                case 'string':
                    if(is_a(User::class, Enum::class, true)) {
                        $items[$key] = User::fromName($item);
                    } else {
                        throw new UnexpectedValueException('fromArray can not create User from string on index ' . $key);
                    }
                    break;    
                default:
                    if ($type !== 'User') {
                        throw new UnexpectedValueException('fromArray expects items of User but has ' . $type . ' on index ' . $key);
                    }
                    break;
            }
            
        }
        return new self($items);
    }
    public function toArray() {
        $return = [];
        foreach ($this->items as $item) {
            if(is_a(User::class, ValueObject::class, true) || is_a(User::class, Set::class, true)) {
                $return[] = $item->toArray();
            }
            
            if(is_a(User::class, Enum::class, true)) {
                $return[] = $item->toString();
            }
        }
        
        return $return;
    }
    public function equals(?self $other): bool
    {
        $ref = $this->toArray();
        $val = $other->toArray();
                
        return ($ref === $val);
    }    
    
    public function contains(User $item): bool {
        return array_search($item, $this->items) !== false;
    }
    
    public function count(): int
    {
        return count($this->items);
    }
    
        public function offsetExists($offset) {
        return isset($this->items[$offset]);
    }

    public function offsetGet($offset) {
        return $this->items[$offset];
    }

    public function current() {
        return $this->items[$this->position];
    }

    public function rewind() {
        $this->position = 0;
    }

    public function key() {
        return $this->position;
    }

    public function next() {
        ++$this->position;
    }

    public function valid() {
        return isset($this->items[$this->position]);
    }
    
    public function add(User $item): self {
        array_push($this->items,$item);
        return $this;
    }

    public function offsetSet($offset, $value) {
        if (empty($offset)) {
            array_push($this->items, $value);
        } else {
            $this->items[$offset] = $value;
        }
    }

    public function offsetUnset($offset) {
        unset($this->items[$offset]);
        $this->items = array_values($this->items);
    }
    
    public function remove(User $item): self {
        $values = $this->toArray();
        if(($key = array_search($item->toArray(), $values)) !== false) {
            unset($this->items[$key]);
        }
        
        $this->items = array_values($this->items);
        return $this;
    }
}